pipeline {
  agent any
  tools {
      jdk 'jdk11'
      maven 'maven'
  }
  stages {
      stage('Install') {
      	steps {
      		dir("Lab4/ua_tqs_gs20/gs-employee-mngr/") {
      			sh "mvn clean install"
      		}
      	}
      	post {
      	    	always {
      	        	unit '**/target/*-reports/TEST-*.xml'
      	   	}           
      	} 
      }
  }
}

