package ua.tqs.AirQuality;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class TqshomeworkTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/opt/WebDriver/bin/geckodriver");  
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tqshomework() {
    this.driver.get("http://localhost:4200/home"); 
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("TQS Air Quality Minimalist Web App"));
    driver.findElement(By.cssSelector(".input-group-append:nth-child(2) .svg-inline--fa")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".input-group-append:nth-child(2) .svg-inline--fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("inputCity")).click();
    driver.findElement(By.id("inputCity")).sendKeys("Lisbon");
    driver.findElement(By.cssSelector(".input-group-append:nth-child(2) > .btn")).click();
    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Entrecampos, Lisboa, Portugal"));
    {
      String value = driver.findElement(By.cssSelector(".text-item > p:nth-child(2)")).getText();
      assertThat(value, is("Latitude: 38.748611111111"));
    }
    {
      String value = driver.findElement(By.cssSelector(".text-item > p:nth-child(3)")).getText();
      assertThat(value, is("Longitude: -9.1488888888889"));
    }
    driver.findElement(By.cssSelector("button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("TQS Air Quality Minimalist Web App"));
    driver.findElement(By.cssSelector(".input-group-append:nth-child(1) .svg-inline--fa")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".input-group-append:nth-child(1) .svg-inline--fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("inputLat")).click();
    driver.findElement(By.id("inputLat")).sendKeys("11");
    driver.findElement(By.id("inputLon")).click();
    driver.findElement(By.id("inputLon")).sendKeys("10");
    driver.findElement(By.cssSelector(".input-group-append:nth-child(1) > .btn")).click();
    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    //assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Abuja US Embassy, Nigeria"));
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("N'Djamena US Embassy, Chad"));
    {
      String value = driver.findElement(By.cssSelector(".text-item > p:nth-child(2)")).getText();
      //assertThat(value, is("Latitude: 9.0416479110718"));
      assertThat(value, is("Latitude: 12.1348"));
    }
    {
      String value = driver.findElement(By.cssSelector(".text-item > p:nth-child(3)")).getText();
      //assertThat(value, is("Longitude: 7.4773740768433"));
      assertThat(value, is("Longitude: 15.0557"));
    }
  }
}
